### ISSUE TITLE
Possible Criterion: API Gateway features?

### ISSUE THREAD

**Issue by jthomas** [Stacksenseio/Evaluation-Criteria#10]
Could the API Gateway criterion be expanded to a separate section to evalulate common features serverless developers need? 

Here's a list of capabilities developers often need.... 

- Rate limiting.
- User authenticaiton & OAuth.
- CORS support.
- Path routing and named parameters.
- Traffic shaping between versions.

API Gateway integration seems to vary between providers feature-wise. Comparing just on "function invocations from HTTP requests" might be less helpful.

_disclosure: I work for IBM as an advocate for serverless and am an openwhisk committer._

**Comment by krishnan** [comment]
Added everything you listed. As far as named parameters, I am wondering if I should just add about using wildcard as an evaluation feature than going deep on it?

**Comment by jthomas** [comment]
@krishnan Sounds sensible.
