### ISSUE TITLE
Possible Criterion: Function Orchestration?

### ISSUE THREAD

**Issue by jthomas** [Stacksenseio/Evaluation-Criteria#11]
There is a lots of interest in orchestration capabilities on serverless platforms. These tools or services allow developers to create "meta or higher-order services" from existing functions without writing more code. OpenWhisk has [action sequences](https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md#creating-action-sequences) and, more recently, [conductor actions](https://github.com/apache/incubator-openwhisk/blob/master/docs/conductors.md) for this. AWS has step functions. I also thought Azure Functions has something in this space but can't find it.

Would this be a valid additional criterion? 

_disclosure: I work for IBM as an advocate for serverless and am an openwhisk committer._

**Comment by krishnan** [comment]
I sort of abstracted it out using Visual Workflow Editor for now. As FaaS matures, I will definitely bring it out in a more finegraned way. Feel free to re-open this issue if you think there is a solid reason to spell it out
