### ISSUE TITLE
Sreams

### ISSUE THREAD

**Issue by rjhintz** [Stacksenseio/Evaluation-Criteria#2]
Is stream handling sufficiently different from handling of classical data structures to be worth calling out separately?

**Comment by yaronha** [comment]
@krishnan @rjhintz  agree, stream require handling of shards/partitions distribution across function instances and things like ordering, checkpointing, etc. AFAIK only AWS Lambda and [nuclio](https://github.com/nuclio/nuclio) support true stream, others are limited to a single kafka shard or only support Async mode (not handling order or key based partitioning)

**Comment by krishnan** [comment]
Added
