### ISSUE TITLE
Add cold/warm start options 

### ISSUE THREAD

**Issue by yaronha** [Stacksenseio/Evaluation-Criteria#4]
im many FaaS you have cold start, in some you can specify if you want warm/cold and the actual scale or range (min/max number of instances) 

Since cold start has a significant penalty it can be nice to specify if the platform support Warm start as well, and what is the timeout

**Comment by krishnan** [comment]
Added the warm start support but didn't add timeout because I have to rely on third party blog posts. Maybe, we can revisit when we do benchmarks.
