### ISSUE TITLE
Built-in logging

### ISSUE THREAD

**Issue by yaronha** [Stacksenseio/Evaluation-Criteria#5]
Another category can be if the FaaS has a built-in Logging & Monitoring capability (i.e. the user can use log object to log/debug into a managed log and monitoring service) 

can specify details such is if the log support structured logging, does it support specifing log-level in runtime and if debug is intrusive (adds overhead of processing & storage when not in debug mode), what are the supported log targets, etc.

**Comment by krishnan** [comment]
Added
