### ISSUE TITLE
Add basic performance 

### ISSUE THREAD

**Issue by yaronha** [Stacksenseio/Evaluation-Criteria#6]
Worth having some basic performance numbers, not suggesting a full benchmark but there are many published posts on the expected latency in cold/warm start and the level of concurrency (e.g. whats the total events/sec processed with N number of clients)

Performance & efficiency is a very important criteria in eval of FaaS
We are working on creating a standard FaaS benchmarking kit based on [HTTP Blaster](https://github.com/v3io/http_blaster) and will propose it to CNCF

**Comment by krishnan** [comment]
I thought about this already. Since it is not going to be our data, we will have to take the brickbats for data taken from third party sources. We intend to do some benchmarks as a future project
