### ISSUE TITLE
Added Criterion: Documentation

### ISSUE THREAD

**Issue by rjhintz** [Stacksenseio/Evaluation-Criteria#7]
Propose adding documentation, possibly with some of these subheadings:

- API <- should API issues be called out separately?
- wiki
- tutorials
- examples
- videos
- documentation "freshness," where the doc tracks the released function
- contribution style. That is, is the doc housed someplace where the community can contribute?

**Comment by krishnan** [comment]
Thanks. Added them. Right now, I am keeping it at a higher level as API Documentation. We can fine tune it at a later stage.
