### ISSUE TITLE
Added Criterion: "End to End" Transaction Cost

### ISSUE THREAD

**Issue by rjhintz** [Stacksenseio/Evaluation-Criteria#8]
The "inexpensive" FaaS can be a lot more expensive when considered end-to-end during the entire "transaction bracket" or counting all the activity from the event trigger by the customer to delivery of the result to the customer.

Is this worth mentioning somehow? It involves all the components in the FaaS "life cycle."

**Comment by krishnan** [comment]
I didn't want to go into the cost factor in this evaluation. That should be a separate stufy altogether based on the workloads. Maybe, for future research
